// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfynpwzxyoxkzxfygebi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmeW5wd3p4eW94a3p4ZnlnZWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQzNjEsImV4cCI6MjA2NTUxMDM2MX0.Cs3LxCddEBROzTyKBXlG4AAjEtcm6gY9B2cbYJQyk4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);